# Generated by Django 2.2.23 on 2021-12-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_taskreport_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Crashed'), (3, 'Finished'), (4, 'Canceled')], default=0),
        ),
    ]
