# Generated by Django 2.2.23 on 2021-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_ocrmodel_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='postgres_language',
            field=models.CharField(default='simple', max_length=64),
        ),
    ]
