# Generated by Django 2.2.24 on 2021-11-09 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_auto_20211008_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_username', models.CharField(max_length=256)),
                ('cluster_hostname', models.CharField(max_length=256)),
                ('base_workdir', models.CharField(max_length=512)),
                ('job_workdir', models.CharField(max_length=36)),
                ('last_known_state', models.CharField(max_length=3)),
                ('job_id', models.CharField(default='', max_length=256)),
                ('django_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
