# Generated by Django 2.2.24 on 2021-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_clusterjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterjob',
            name='last_known_state',
            field=models.CharField(max_length=20),
        ),
    ]
