# Generated by Django 2.2.27 on 2022-03-25 10:27

import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20210730_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='blank_char',
            field=models.CharField(blank=True, default=' ', max_length=1),
        ),
    ]
