# Generated by Django 2.2.24 on 2021-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20211109_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterjob',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
