# Generated by Django 2.2.24 on 2021-11-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_clusterjob_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
