# Generated by Django 2.2.24 on 2021-11-24 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20211124_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
